# Generated by Django 4.2.5 on 2023-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
